name: Java CICD pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile

  trivy-scan:
    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v5
    - name: installing trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y

    - name: Trivy scan
      run: trivy fs --format table -o fs-report.html .
    - name: gitleaks Installation
      run: sudo apt-get install gitleaks -y
    - name: gitleaks scan 
      run: gitleaks detect source . -r gitleaks-reports.json -f json 
      
      
      
   

        

      
        

