name: Java CICD pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: Agent-1
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile

      
        

